# -*- mode: ruby -*-
# vi: set ft=ruby :

# Fail if the vagrant-disksize plugin is not installed
unless Vagrant.has_plugin?("vagrant-vbguest")
  raise 'vagrant-vbguest is not installed!'
end

# Fail if the vagrant-disksize plugin is not installed
unless Vagrant.has_plugin?("vagrant-hostmanager")
  raise 'vagrant-hostmanager is not installed!'
end

# Fail if the vagrant-disksize plugin is not installed
unless Vagrant.has_plugin?("vagrant-disksize")
  raise 'vagrant-disksize is not installed!'
end

Vagrant.configure("2") do |config|
  config.vm.box = "centos7"
  #config.vm.define "cdp-7-1-7"
  config.vm.define "cdp-base"
  config.vbguest.installer_options = { allow_kernel_upgrade: true }
  config.vm.network "public_network", ip: "192.168.1.10"
  config.vm.network "private_network", ip: "192.168.200.33", virtualbox__intnet: "08net"
  config.vm.network :forwarded_port, guest: 7180, host: 7180
  config.vm.network :forwarded_port, guest: 8889, host: 8889
  config.vm.network :forwarded_port, guest: 9870, host: 9870
  config.vm.network :forwarded_port, guest: 6080, host: 6080
  config.vm.network :forwarded_port, guest: 21050, host: 21050
  config.vm.network :forwarded_port, guest: 9991, host: 9991
  config.vm.network :forwarded_port, guest: 8051, host: 8051
  config.vm.network :forwarded_port, guest: 8088, host: 8088
  config.vm.network :forwarded_port, guest: 19888, host: 19888
  config.vm.network :forwarded_port, guest: 25020, host: 25020
  config.vm.network :forwarded_port, guest: 18211, host: 18211
  config.vm.network :forwarded_port, guest: 18121, host: 18121
  config.vm.network :forwarded_port, guest: 9092, host: 9092
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.network :forwarded_port, guest: 9090, host: 9090

  config.vm.hostname = "localhost.localdomain"
  config.disksize.size = "200GB"
  config.vm.disk :disk, size: "200GB", name: "extra_storage"  
  config.vm.provision "shell", path: "VMSetup.sh", args: "<change_me_for_username> <change_me_for_password> templates/onenodecluster.json"

  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
     # Customize the amount of memory on the VM:
     vb.memory = "28000"
     vb.cpus = "9"
   end
end
